protected/modules/admin/controllers/VehicleController.php
<?php

class VehicleController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
    public $layout = "/layouts/main";

    public $canWithoutLogin = array();
    function init() {
        $this->canWithoutLogin = array('login');

        if(!isset(Yii::app()->session['admin'])) {
            if (!in_array($this->action, $this->canWithoutLogin)) {
                $this->redirect($this->CreateUrl('default/login'));
            }
        }
    }
	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
				'users'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Vehicle;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);
        if(isset($_POST['Vehicle']))
        {
            $model->attributes=$_POST['Vehicle'];
            if($_FILES['Vehicle']){
                $uploads_dir = UPLOADS.'vehicle/';
                $tmp_name = $_FILES["Vehicle"]["tmp_name"]["image"];
                $tmp_name1 = $_FILES["Vehicle"]["tmp_name"]["history_image"];
                $model->image = md5(time()).".png";
                $model->history_image = md5(time()+1).".png";
                @move_uploaded_file($tmp_name, "$uploads_dir/$model->image");
                @move_uploaded_file($tmp_name1, "$uploads_dir/$model->history_image");
            }
            if($model->save())
                $this->redirect(array('view','id'=>$model->id));
        }

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

        if(isset($_POST['Vehicle']))
        {
            $oldImage = $model->image;
            $oldImage1 = $model->history_image;
            $model->attributes = $_POST['Vehicle'];
            $model->image = $oldImage;
            $model->history_image = $oldImage1;
            if(!empty($_FILES['Vehicle']['name']['image'])){
                if(file_exists(UPLOADS.'/vehicle/'. $model->image)){
                    unlink(bDIR.'/upload/vehicle/'. $model->image);
                }
                $imageName = md5(time()).".png";
                $model->image = $imageName;
                $dir = UPLOADS."vehicle/";
                $tmp_name = $_FILES["Vehicle"]["tmp_name"]["image"];
                $file = $dir.$imageName;

                move_uploaded_file($tmp_name, "$dir/$model->image");
            }
            if(!empty($_FILES['Vehicle']['name']['history_image'])){
                if(file_exists(UPLOADS.'/vehicle/'. $model->history_image)){
                    unlink(bDIR.'/upload/vehicle/'. $model->history_image);
                }
                $imageName = md5(time()+1).".png";
                $model->history_image = $imageName;
                $dir = UPLOADS."vehicle/";
                $tmp_name = $_FILES["Vehicle"]["tmp_name"]["history_image"];
                $file = $dir.$imageName;

                move_uploaded_file($tmp_name, "$dir/$model->history_image");
            }

            if($model->save())
                $this->redirect(array('view','id'=>$model->id));
        }

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Vehicle');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Vehicle('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Vehicle']))
			$model->attributes=$_GET['Vehicle'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Vehicle the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Vehicle::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Vehicle $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='vehicle-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/modules/admin/views/vehicle/_form.php
<!-- Main content -->
<section class="content">
	<div class="row">
		<!-- left column -->
		<div class="col-md-12">
			<!-- general form elements -->
			<div class="box box-primary">
				<div class="box-header with-border">
					<h3 class="box-title"><p class="note">Fields with <span class="required">*</span> are required.</p></h3>
				</div>

				<?php $form=$this->beginWidget('CActiveForm', array(
					'id'=>'person-number-form',
					'htmlOptions' => array(
						'class' =>'form-horizontal',
						"enctype" => "multipart/form-data"
					),
					'enableAjaxValidation'=>false,
				)); ?>

				<?php echo $form->errorSummary($model); ?>

				<div class="row form-group">
					<?php echo $form->labelEx($model,'vehicle_volume',array('class'=>'col-sm-2 control-label')); ?>
					<div class="col-sm-10">
						<?php echo $form->textField($model,'vehicle_volume',array('class' => 'form-control')); ?>
					</div>
					<?php echo $form->error($model,'vehicle_volume'); ?>
				</div>
				<div class="row form-group">
					<?php echo $form->labelEx($model,'price',array('class'=>'col-sm-2 control-label')); ?>
					<div class="col-sm-10">
						<?php echo $form->textField($model,'price',array('class' => 'form-control')); ?>
					</div>
					<?php echo $form->error($model,'price'); ?>
				</div>

				<div class="row form-group">
					<?php echo $form->labelEx($model,'image',array('class'=>'col-sm-2 control-label')); ?>
					<div class="col-sm-10">
						<?php echo $form->fileField($model,'image',array('class' => 'form-control')); ?>
					</div>
					<?php echo $form->error($model,'image'); ?>
				</div>

				<div class="row form-group">
					<?php echo $form->labelEx($model,'history_image',array('class'=>'col-sm-2 control-label')); ?>
					<div class="col-sm-10">
						<?php echo $form->fileField($model,'history_image',array('class' => 'form-control')); ?>
					</div>
					<?php echo $form->error($model,'history_image'); ?>
				</div>

				<div class="form-group buttons">
					<div class="col-sm-12">
						<?php echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'Save',array('class'=>'btn btn-primary pull-right')); ?>
					</div>
				</div>


				<?php $this->endWidget(); ?>

			</div>
		</div>
	</div>
</section>

protected/modules/admin/views/vehicle/_search.php
<?php
/* @var $this VehicleController */
/* @var $model Vehicle */
/* @var $form CActiveForm */
?>

<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'id'); ?>
		<?php echo $form->textField($model,'id',array('size'=>11,'maxlength'=>11)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'image'); ?>
		<?php echo $form->textField($model,'image',array('size'=>60,'maxlength'=>250)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'history_image'); ?>
		<?php echo $form->textField($model,'history_image',array('size'=>60,'maxlength'=>250)); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

protected/modules/admin/views/vehicle/_view.php
<?php
/* @var $this VehicleController */
/* @var $data Vehicle */
?>

<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id), array('view', 'id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('image')); ?>:</b>
	<?php echo CHtml::encode($data->image); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('history_image')); ?>:</b>
	<?php echo CHtml::encode($data->history_image); ?>
	<br />


</div>

protected/modules/admin/views/vehicle/admin.php
<section class="content-header">
	<h1>
		Persons quantity
	</h1>

</section>
<section class="content">
	<div class="row">
		<div class="col-xs-12">
			<div class="box">
				<div class="box-header">
					<h3 class="box-title">Persons quantity</h3>
					<a href="<?=$this->CreateUrl('vehicle/create')?>" class="btn btn-primary pull-right">Add New</a>
				</div>
				<!-- /.box-header -->
				<div class="box-body">

					<?php $this->widget('zii.widgets.grid.CGridView', array(
						'id'=>'vehicle-grid',
						'itemsCssClass' => 'table table-bordered table-hover',
						'dataProvider'=>$model->search(),
						'filter'=>$model,
						'columns'=>array(
							'vehicle_volume',
							'price',
							array(
								'name'=>'image',
								'type' => 'raw',
								'htmlOptions'=>array(
									'class' => 'admin_img'
								),
								'value' => 'CHtml::image(Yii::app()->baseUrl . "/upload/vehicle/" . $data->image)'
							),
							array(
								'name'=>'history_image',
								'type' =>'raw',
								'htmlOptions'=>array(
									'class'=>'admin_img'
								),
								'value' => 'CHtml::image(Yii::app()->baseUrl . "/upload/vehicle/" . $data->history_image)'
							),
							array(
								'class' => 'zii.widgets.grid.CButtonColumn',
								'htmlOptions' => array('style' => 'white-space: nowrap'),
								'afterDelete' => 'function(link,success,data) { if (success && data) alert(data); }',
								'buttons' => array(
									'view' => array(
										'options' => array('rel' => 'tooltip', 'data-toggle' => 'tooltip', 'title' => Yii::t('app', 'View'),'class'=>'img-btn'),
										'label' => '<i class="fa fa-eye"></i>',
										'imageUrl' => false,
									),
									'update' => array(
										'options' => array('rel' => 'tooltip', 'data-toggle' => 'tooltip', 'title' => Yii::t('app', 'Update'),'class'=>'img-btn'),
										'label' => '<i class="fa fa-pencil"></i>',
										'imageUrl' => false,
									),
									'delete' => array(
										'options' => array('rel' => 'tooltip', 'data-toggle' => 'tooltip', 'title' => Yii::t('app', 'Delete'),'class'=>'img-btn del-btn'),
										'label' => '<i class="fa fa-times"></i>',
										'imageUrl' => false,
									)
								)
							),
						),
					)); ?>
				</div>
			</div>
		</div>
	</div>
</section>

protected/modules/admin/views/vehicle/create.php
<?php
/* @var $this VehicleController */
/* @var $model Vehicle */

$this->breadcrumbs=array(
	'Vehicles'=>array('index'),
	'Create',
);

$this->menu=array(
	array('label'=>'List Vehicle', 'url'=>array('index')),
	array('label'=>'Manage Vehicle', 'url'=>array('admin')),
);
?>

<h1>Create Vehicle</h1>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

protected/modules/admin/views/vehicle/index.php
<?php
/* @var $this VehicleController */
/* @var $dataProvider CActiveDataProvider */

$this->breadcrumbs=array(
	'Vehicles',
);

$this->menu=array(
	array('label'=>'Create Vehicle', 'url'=>array('create')),
	array('label'=>'Manage Vehicle', 'url'=>array('admin')),
);
?>

<h1>Vehicles</h1>

<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>

protected/modules/admin/views/vehicle/update.php
<?php
/* @var $this VehicleController */
/* @var $model Vehicle */

$this->breadcrumbs=array(
	'Vehicles'=>array('index'),
	$model->id=>array('view','id'=>$model->id),
	'Update',
);

$this->menu=array(
	array('label'=>'List Vehicle', 'url'=>array('index')),
	array('label'=>'Create Vehicle', 'url'=>array('create')),
	array('label'=>'View Vehicle', 'url'=>array('view', 'id'=>$model->id)),
	array('label'=>'Manage Vehicle', 'url'=>array('admin')),
);
?>

<h1>Update Vehicle <?php echo $model->id; ?></h1>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

protected/modules/admin/views/vehicle/view.php
<section class="content-header">
	<h1>
		Vehicle
		<small>#<?php echo $model->id; ?></small>
	</h1>

</section>
<section class="content">
	<div class="row">
		<div class="col-xs-12">
			<div class="box">
				<div class="box-header">
					<h3 class="box-title">Vehicle #<?php echo $model->id; ?></h3>
					<a href="<?=$this->CreateUrl('vehicle/update/id/'.$model->id)?>" class="btn btn-success pull-right" style="margin-left: 15px">Edit</a>
					<a href="<?=$this->CreateUrl('vehicle/create')?>" class="btn btn-primary pull-right">Add New</a>
				</div>

				<?php $this->widget('zii.widgets.CDetailView', array(
					'data'=>$model,
					'htmlOptions' => array('class' => 'table table-bordered table-hover'),
					'attributes'=>array(
						'id',
						'vehicle_volume',
						'price',
						array(
							'name'=>'image',
							'type'=>'raw',
							'value'=>CHtml::image(Yii::app()->baseUrl . "/upload/vehicle/" . $model->image)
						),
						array(
							'name'=>'history_image',
							'type'=>'raw',
							'value'=>CHtml::image(Yii::app()->baseUrl . "/upload/vehicle/" . $model->history_image)
						),
					),
				)); ?>
			</div>
		</div>
	</div>
	</div>
</section>