protected/modules/admin/controllers/InsuranceController.php
<?php

class InsuranceController extends Controller
{
    /**
     * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
     * using two-column layout. See 'protected/views/layouts/column2.php'.
     */


    public $layout = "/layouts/main";

    public $canWithoutLogin = array();
    function init() {
        $this->canWithoutLogin = array('login');

        if(!isset(Yii::app()->session['admin'])) {
            if (!in_array($this->action, $this->canWithoutLogin)) {
                $this->redirect($this->CreateUrl('default/login'));
            }
        }
    }
    /**
     * @return array action filters
     */
    public function filters()
    {
        return array(
            'accessControl', // perform access control for CRUD operations
            'postOnly + delete', // we only allow deletion via POST request
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules()
    {
        return array(
            array('allow',  // allow all users to perform 'index' and 'view' actions
                'actions'=>array('index','view'),
                'users'=>array('*'),
            ),
            array('allow', // allow authenticated user to perform 'create' and 'update' actions
                'actions'=>array('create','update'),
                'users'=>array('@'),
            ),
            array('allow', // allow admin user to perform 'admin' and 'delete' actions
                'actions'=>array('admin','delete'),
                'users'=>array('admin'),
            ),
            array('deny',  // deny all users
                'users'=>array('*'),
            ),
        );
    }

    /**
     * Displays a particular model.
     * @param integer $id the ID of the model to be displayed
     */
    public function actionView($id)
    {
        $this->render('view',array(
            'model'=>$this->loadModel($id),
        ));
    }

    /**
     * Creates a new model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     */
    public function actionCreate()
    {

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        $model=new Insurance;

        if(isset($_POST['rowGroup']))
        {
//			Helpers::dump($_POST);die;
            foreach ($_POST['rowGroup'] as $value){
                $model=new Insurance;
                $model->price = $value['price'];
                if($model->save()){
                    foreach ($value['text'] as $k=>$v){

                        $modelLabel = new InsuranceLabel;
                        $modelLabel->insurance_id =$model->id;
                        $modelLabel->language_id =$k;
                        $modelLabel->text=$v;
                        $modelLabel->save();
                    }


                }
            }
            $this->redirect(array('admin',));
        }

        $this->render('create',array(
            'model'=>$model,
        ));
    }

    /**
     * Updates a particular model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id the ID of the model to be updated
     */
    public function actionUpdate($id)
    {
        $model=$this->loadModel($id);

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if(isset($_POST['rowGroup']))
        {

            $model->attributes=$_POST['rowGroup'];
            if($model->save()){

                $languages = Helpers::languages();
                if(isset($languages)){
                    foreach($languages as $key=>$value){

                        $modelLabel = InsuranceLabel::model()->findByAttributes(array('insurance_id' => $id,'language_id' =>$value->id));
                        $modelLabel->text = $_POST['rowGroup']['text'][$value->id];

                        $modelLabel->save();
                    }

                }


                $this->redirect(array('view','id'=>$model->id));

            }
        }
        $this->render('update',array(
            'model'=>$model,
        ));
    }

    /**
     * Deletes a particular model.
     * If deletion is successful, the browser will be redirected to the 'admin' page.
     * @param integer $id the ID of the model to be deleted
     */
    public function actionDelete($id)
    {
        $this->loadModel($id)->delete();

        // if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
        if(!isset($_GET['ajax']))
            $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
    }

    /**
     * Lists all models.
     */
    public function actionIndex()
    {
        $dataProvider=new CActiveDataProvider('Insurance');
        $this->render('index',array(
            'dataProvider'=>$dataProvider,
        ));
    }

    /**
     * Manages all models.
     */
    public function actionAdmin()
    {
        $model=new Insurance('search');


        $model->unsetAttributes();  // clear any default values
        if(isset($_GET['Insurance']))
            $model->attributes=$_GET['Insurance'];
//		Helpers::dump($model);
        $this->render('admin',array(
            'model'=>$model,
        ));
    }

    /**
     * Returns the data model based on the primary key given in the GET variable.
     * If the data model is not found, an HTTP exception will be raised.
     * @param integer $id the ID of the model to be loaded
     * @return Insurance the loaded model
     * @throws CHttpException
     */
    public function loadModel($id)
    {
        $model=Insurance::model()->findByPk($id);
        if($model===null)
            throw new CHttpException(404,'The requested page does not exist.');
        return $model;
    }

    /**
     * Performs the AJAX validation.
     * @param Insurance $model the model to be validated
     */
    protected function performAjaxValidation($model)
    {
        if(isset($_POST['ajax']) && $_POST['ajax']==='insurance-form')
        {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }
    }
}

protected/modules/admin/views/insurance/_form.php
<!-- Main content -->
<section class="content">
	<div class="row">
		<!-- left column -->
		<div class="col-md-12">
			<!-- general form elements -->
			<div class="box box-primary">
				<div class="box-header with-border">
					<h3 class="box-title"><p class="note">Fields with <span class="required">*</span> are required.</p></h3>
				</div>


				<?php $form=$this->beginWidget('CActiveForm', array(
					'id'=>'insurance-form',
					// Please note: When you enable ajax validation, make sure the corresponding
					// controller action is handling ajax validation correctly.
					// There is a call to performAjaxValidation() commented in generated controller code.
					// See class documentation of CActiveForm for details on this.
					'enableAjaxValidation'=>false,
				)); ?>

				<?php echo $form->errorSummary($model); ?>

				<div class="form-container row">
					<div class="col-xs-12">
						<div class="row form-group">
							<?php echo $form->labelEx($model,'price',array('class'=>'col-sm-2 control-label')); ?>
							<div class="col-sm-10">
								<?php if($model->isNewRecord): ?>
									<?php echo $form->textField($model,'price',array('class' => 'form-control', 'name'=>'rowGroup[0][price]')); ?>

								<?php else: ?>
									<?php echo $form->textField($model,'price',array('class' => 'form-control', 'name'=>'rowGroup[price]')); ?>

								<?php endif;?>
							</div>
							<?php echo $form->error($model,'price'); ?>
						</div>
					</div>
					<div class="col-xs-12">
						<div class="form-group">
							<?php
							$languages = Helpers::languages();
							if(!empty($languages)):
								foreach($languages as $key => $value):
									?>
									<?php
									$active = "";
									if($key == 0){
										$active = "active";
									}
									$content = InsuranceLabel::model()->findByAttributes(array('language_id' => $value->id,'insurance_id' => $model->id));
									$name = "";
									if(!empty($content)){
										$name = $content->text;
									}
									?>
									<label class="col-sm-2 control-label"><?=$value->name?></label>
									<div class="col-sm-10">
										<div class="form-group row">
											<div class="col-sm-12">
												<?php 									if($model->isNewRecord):
													?>
													<textarea type="text" class="form-control margin_10" name="rowGroup[0][text][<?=$value->id?>]" id="editor-0-<?=$value->id?>"  required><?=$name?></textarea>
												<?php else: ?>
													<textarea type="text" class="form-control margin_10" name="rowGroup[text][<?=$value->id?>]" id="editor-0-<?=$value->id?>"  required><?=$name?></textarea>
												<?php endif?>
											</div>
										</div>
									</div>
									<?php
								endforeach;
							endif;
							?>
						</div>
					</div>
				</div>
				<div class="form-container rows row">

				</div>

				<div class="form-group">
					<?php if($model->isNewRecord): ?>

						<div class="col-sm-12">
							<button class="btn btn-primary pull-right" data-id="1" id="plus">+</button>
						</div>
					<?php endif; ?>
				</div>
				<div class="col-xs-12">
				</div>
				<div class="form-group buttons">
					<div class="col-sm-12">
						<?php echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'Save',array('class'=>'btn btn-primary pull-right')); ?>
					</div>
				</div>
				<?php $this->endWidget(); ?>
			</div>
		</div>
	</div>
</section>
<script>
	$(function () {
		// Replace the <textarea id="editor1"> with a CKEditor
		// instance, using default configuration.
		<?php
		$language = Helpers::languages();
		if(!empty($language)):
		foreach($language as $key => $value):
		?>
		CKEDITOR.replace( 'editor-0-<?=$value->id?>', {});
		//bootstrap WYSIHTML5 - text editor
		$(".textarea").wysihtml5();
		<?php
		endforeach;
		endif;
		?>
	});
</script>

<script>
	$(document).ready(function () {
		$('#plus').on("click",function(e){
			e.preventDefault();
			var current = $(this).attr('data-id');
			var strVar="";
			strVar += "<div class=\"container-"+current+"\" style = 'margin-top: 50px;float: left;width: 100%;'>";
			strVar += "							<div class=\"col-xs-12\">";
			strVar += "								<div class=\"row form-group\">";
			strVar += "									<label class=\"col-sm-2 control-label\">Price *<\/label>";
			strVar += "									<div class=\"col-xs-10\">";
			strVar += "										<input name=\"rowGroup["+current+"][price]\" class=\"form-control\" \/>";
			strVar += "									<\/div>";
			strVar += "								<\/div>";
			<?php
			$language = Helpers::languages();
			if(!empty($language)):
			foreach($language as $key => $value):
			?>
			strVar += "								<div class=\"row form-group\">";
			strVar += "									<label class=\"col-sm-2 control-label\">Text * <?=$value->name?> <\/label>";
			strVar += "									<div class=\"col-xs-10\">";
			strVar += "										<textarea name=\"rowGroup["+current+"][text][<?=$value->id?>]\" id=\"editor-"+current+"-<?=$value->id?>\" class=\"form-control\" ></textarea>";
			strVar += "									<\/div>";
			strVar += "								<\/div>";
			strVar += "							<\/div>";
			<?php
			endforeach;
			endif;
			?>

			strVar += "						<\/div>";

			$('.rows').append(strVar);

			$(function () {
				// Replace the <textarea id="editor1"> with a CKEditor
				// instance, using default configuration.
				<?php
				$language = Helpers::languages();
				if(!empty($language)):
				foreach($language as $key => $value):
				?>
				CKEDITOR.replace( 'editor-'+current+'-<?=$value->id?>', {});
				//bootstrap WYSIHTML5 - text editor
				$(".textarea").wysihtml5();
				<?php
				endforeach;
				endif;
				?>
			});

			current = parseInt(current)+1;
			$(this).attr('data-id',current);
		});
	});
</script>

protected/modules/admin/views/insurance/_search.php
<?php
/* @var $this InsuranceController */
/* @var $model Insurance */
/* @var $form CActiveForm */
?>

<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'id'); ?>
		<?php echo $form->textField($model,'id',array('size'=>11,'maxlength'=>11)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'price'); ?>
		<?php echo $form->textField($model,'price'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

protected/modules/admin/views/insurance/_view.php
<?php
/* @var $this InsuranceController */
/* @var $data Insurance */
?>

<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id), array('view', 'id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('price')); ?>:</b>
	<?php echo CHtml::encode($data->price); ?>
	<br />


</div>

protected/modules/admin/views/insurance/admin.php
<section class="content-header">
	<h1>
		Insurance
	</h1>

</section>
<section class="content">
	<div class="row">
		<div class="col-xs-12">
			<div class="box">
				<div class="box-header">
					<h3 class="box-title">Insurance</h3>
					<a href="<?=$this->CreateUrl('insurance/create')?>" class="btn btn-primary pull-right">Add New</a>
				</div>
				<!-- /.box-header -->
				<div class="box-body">

					<?php
					$this->widget('zii.widgets.grid.CGridView', array(
						'id'=>'insurance-grid',

						'dataProvider'=>$model->search(),
						'itemsCssClass' => 'table table-bordered table-hover',
						'filter'=>$model,
						'columns'=>array(
							'id',
							'price',
							array(
								'class' => 'zii.widgets.grid.CButtonColumn',
								'htmlOptions' => array('style' => 'white-space: nowrap'),
								'afterDelete' => 'function(link,success,data) { if (success && data) alert(data); }',
								'buttons' => array(
									'view' => array(
										'options' => array('rel' => 'tooltip', 'data-toggle' => 'tooltip', 'title' => Yii::t('app', 'View'),'class'=>'img-btn'),
										'label' => '<i class="fa fa-eye"></i>',
										'imageUrl' => false,
									),
									'update' => array(
										'options' => array('rel' => 'tooltip', 'data-toggle' => 'tooltip', 'title' => Yii::t('app', 'Update'),'class'=>'img-btn'),
										'label' => '<i class="fa fa-pencil"></i>',
										'imageUrl' => false,
									),
									'delete' => array(
										'options' => array('rel' => 'tooltip', 'data-toggle' => 'tooltip', 'title' => Yii::t('app', 'Delete'),'class'=>'img-btn del-btn'),
										'label' => '<i class="fa fa-times"></i>',
										'imageUrl' => false,
									)
								)
							),
						),
					)); ?>
				</div>
			</div>
		</div>
	</div>
</section>

protected/modules/admin/views/insurance/create.php
<?php
/* @var $this InsuranceController */
/* @var $model Insurance */

$this->breadcrumbs=array(
	'Insurances'=>array('index'),
	'Create',
);

$this->menu=array(
	array('label'=>'List Insurance', 'url'=>array('index')),
	array('label'=>'Manage Insurance', 'url'=>array('admin')),
);
?>

<h1>Create Insurance</h1>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

protected/modules/admin/views/insurance/index.php
<?php
/* @var $this InsuranceController */
/* @var $dataProvider CActiveDataProvider */

$this->breadcrumbs=array(
	'Insurances',
);

$this->menu=array(
	array('label'=>'Create Insurance', 'url'=>array('create')),
	array('label'=>'Manage Insurance', 'url'=>array('admin')),
);
?>

<h1>Insurances</h1>

<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>

protected/modules/admin/views/insurance/update.php
<?php
/* @var $this InsuranceController */
/* @var $model Insurance */

$this->breadcrumbs=array(
	'Insurances'=>array('index'),
	$model->id=>array('view','id'=>$model->id),
	'Update',
);

$this->menu=array(
	array('label'=>'List Insurance', 'url'=>array('index')),
	array('label'=>'Create Insurance', 'url'=>array('create')),
	array('label'=>'View Insurance', 'url'=>array('view', 'id'=>$model->id)),
	array('label'=>'Manage Insurance', 'url'=>array('admin')),
);
?>

<h1>Update Insurance <?php echo $model->id; ?></h1>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

protected/modules/admin/views/insurance/view.php
<?php
/* @var $this InsuranceController */
/* @var $model Insurance */

$this->breadcrumbs=array(
	'Insurances'=>array('index'),
	$model->id,
);

$this->menu=array(
	array('label'=>'List Insurance', 'url'=>array('index')),
	array('label'=>'Create Insurance', 'url'=>array('create')),
	array('label'=>'Update Insurance', 'url'=>array('update', 'id'=>$model->id)),
	array('label'=>'Delete Insurance', 'url'=>'#', 'linkOptions'=>array('submit'=>array('delete','id'=>$model->id),'confirm'=>'Are you sure you want to delete this item?')),
	array('label'=>'Manage Insurance', 'url'=>array('admin')),
);
?>

<h1>View Insurance #<?php echo $model->id; ?></h1>

<?php $this->widget('zii.widgets.CDetailView', array(
	'data'=>$model,
	'attributes'=>array(
		'id',
		'price',
	),
)); ?>